[package]
name = "plankton"
version = "0.1.0"
edition = "2024"

[dependencies]
avian2d = "0.3.0"
bevy = "0.16.0"
bevy-inspector-egui = "0.31.0"
bevy_ecs_ldtk = { path = "/home/piro/Work/bevy_ecs_ldtk" }
